### ISSUE TITLE
Backend: create a model name post

### ISSUE THREAD

**Issue by tanvirstreame** [banglar-mukti/khabar-bonton#10]
Create 'Post' as a model where necessary attribute will be there. Make proper serializer, urls

**Comment by mhkmcp** [comment]
Created Post model

**Comment by tanvirstreame** [comment]
https://github.com/banglar-mukti/khabar-bonton/pull/14

**Comment by tanvirstreame** [comment]
https://github.com/banglar-mukti/khabar-bonton/pull/14
